# Generated by Django 3.1.14 on 2023-01-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0038_auto_20220512_1800"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcedefinition",
            name="attributeFilter",
            field=models.JSONField(default=dict),
        ),
    ]
