# Generated by Django 4.1.7 on 2023-03-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0040_access_permission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="principal",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="principal",
            name="unique principal username per tenant",
        ),
        migrations.RemoveField(
            model_name="principal",
            name="username",
        ),
        migrations.AddField(
            model_name="principal",
            name="user_id",
            field=models.CharField(db_index=True, default=None, max_length=36, null=True, unique=True),
        ),
    ]
